global:
  scrape_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

scrape_configs:
  - job_name: demo/mimir
    static_configs:
      - targets: ['mimir-1:8080']
        labels:
          pod: 'mimir-1'
      - targets: ['mimir-2:8080']
        labels:
          pod: 'mimir-2'
      - targets: ['mimir-3:8080']
        labels:
          pod: 'mimir-3'

rule_files:
  - ./rules.yml

remote_write:
  - url: http://load-balancer:9009/api/v1/push
    headers:
      X-Scope-OrgID: demo