version: '3.8'

networks:
  monitoring: 
    driver: bridge
  
volumes:
  grafana_data: 
  minio-data:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:

services:
  minio:
    image: minio/minio:latest
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=mimir123
    volumes:
      - minio-data:/data

  grafana_uno:
    image: grafana/grafana-enterprise:latest
    container_name: grafana_uno
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 9000:3000
    networks:
      - monitoring
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./cfg/rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"

  load-balancer:
    image: nginx:latest
    volumes:
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    ports:
      - 9009:9009 

  mimir-1:
    image: grafana/mimir:latest
    command: ["--config.file=/etc/mimir.yml"]
    hostname: mimir-1
    volumes:
      - ./cfg/alertmanager-fallback.yml:/etc/alertmanager-fallback.yml
      - ./cfg/mimir.yml:/etc/mimir.yml
      - mimir-1-data:/data
    depends_on:
      - "minio" 

  mimir-2:
    image: grafana/mimir:latest
    command: ["--config.file=/etc/mimir.yml"]
    hostname: mimir-2
    volumes:
      - ./cfg/alertmanager-fallback.yml:/etc/alertmanager-fallback.yml
      - ./cfg/mimir.yml:/etc/mimir.yml
      - mimir-2-data:/data
    depends_on:
      - "minio" 

  mimir-3:
    image: grafana/mimir:latest
    command: ["--config.file=/etc/mimir.yml"]
    hostname: mimir-3
    volumes:
      - ./cfg/alertmanager-fallback.yml:/etc/alertmanager-fallback.yml
      - ./cfg/mimir.yml:/etc/mimir.yml
      - mimir-3-data:/data
    depends_on:
      - "minio"