global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

remote_write:
  - url: "http://localhost:9090/api/v1/write"
    basic_auth:
      username: "malvi"
      password: "test123"